name: CD
on:
  repository_dispatch:
    types: [run_my_workflow]
  workflow_dispatch:
  push:
    branches: main

env:
  IMAGE_NAME: menstrues
  IMAGE_TAG: latest
  VITE_MSAL_CONFIG_AUTH_CLIENTID: ${{ secrets.VITE_MSAL_CONFIG_AUTH_CLIENTID }}
  VITE_MSAL_CONFIG_AUTH_AUTHORITY: ${{ secrets.VITE_MSAL_CONFIG_AUTH_AUTHORITY }}
  VITE_MSAL_CONFIG_AUTH_REDIRECTUI: ${{ secrets.VITE_MSAL_CONFIG_AUTH_REDIRECTUI }}

jobs:
  build:
    name: Deploy to Github package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.3.0

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1.6.0

      - name: Build project
        run: npm run build
        
      - name: List current directory
        run: ls -al
        
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build and Push image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          build-args: |
            version=${{ env.IMAGE_TAG }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          directory : dist
