name: CD
on:
  repository_dispatch:
    types: [run_my_workflow]
  workflow_dispatch:
  push:
    branches: main

env:
  IMAGE_NAME: menstrues
  IMAGE_TAG: latest

jobs:
  build:
    name: Deploy to Github package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.3.0

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build and Push image
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          build-args: |
            version=${{ env.IMAGE_TAG }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
