name: CDSPIRIA
on:
  workflow_dispatch:
    inputs:
      env_to_deploy:
        type: environment
        description: 'Select an environment'
        required: true
        default: SPIRIAPROD
        
  push:
    branches: main    

jobs:
  build:
    name: Deploy to Spiria static web app
    environment: ${{ github.event.inputs.env_to_deploy }}
    env:
      token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.3.0

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1.6.0

      - name: Build project
        run: npm run build

      - name: Deplo to static web app
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: "/dist"
          skip_app_build: true
          azure_static_web_apps_api_token: ${{ env.token }}
